### ISSUE TITLE
Release version with Node.js Support

### ISSUE THREAD

**Issue by kevgathuku** [mroderick/wrapple#10]
The latest published version on `npm` still does not include this [Node.js patch](https://github.com/mroderick/wrapple/commit/07945cad6c1d1868ba5b8b726c17337a18b9e954)

**Comment by mroderick** [comment]
Thank you for the reminder!

I've published `0.4.0`, which does contain it.

**Comment by kevgathuku** [comment]
Thanks @mroderick
